const BaseModel = require("./BaseModel");
const bcrypt = require("bcryptjs");
const crypto = require("crypto");
const s3Service = require("../services/s3Service");
const { PLANS, REQUIRED_DRIVER_DOCS } = require("../utils/constants");



class Driver extends BaseModel {
  static tableName = "drivers";
  static _pingCounters = new Map();

  static async findByEmail(email) {
    const result = await this.query("SELECT * FROM drivers WHERE email = $1", [
      email,
    ]);
    return result.rows[0];
  }

  static async create(driverData) {
    const { name, email, password, phone, vehicle_type, vehicle_plate, date_of_birth } =
      driverData;
    const password_hash = await bcrypt.hash(password, 12);

    // TEMPORARY TEST-MODE BYPASS — remove before real launch.
    // When DRIVER_TEST_MODE=true (Render env var), a brand-new driver
    // registration only:
    //   1. starts 'approved' instead of 'pending_documents'
    //   2. gets a real driver_documents row per REQUIRED_DRIVER_DOCS,
    //      pre-verified, so the admin/approval views show a complete,
    //      consistent document set rather than an approved driver with
    //      zero documents on file
    //   3. gets a real driver_subscriptions row (the same 'monthly' plan
    //      real drivers can buy, just not charged), so
    //      checkDriverSubscriptionAllowed's real, unmodified check passes
    //      naturally — no separate bypass needed there
    // This only ever runs at the moment of registration. An existing
    // account signing in later is untouched — this function is never
    // called again for it. Revert to always "pending_documents" with no
    // extra inserts before going live; see subscriptionService.js for the
    // matching real-check-stays-real reasoning.
    const testMode = process.env.DRIVER_TEST_MODE === "true";
    const initialStatus = testMode ? "approved" : "pending_documents";

    if (!testMode) {
      return await super.create(this.tableName, {
        name,
        email,
        password_hash,
        phone,
        vehicle_type: vehicle_type || null,
        vehicle_plate: vehicle_plate || null,
        status: initialStatus,
        date_of_birth: date_of_birth || null,
      });
    }

    return await this.transaction(async (client) => {
      const driverResult = await client.query(
        `INSERT INTO drivers (name, email, password_hash, phone, vehicle_type, vehicle_plate, status, date_of_birth)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,
        [
          name,
          email,
          password_hash,
          phone,
          vehicle_type || null,
          vehicle_plate || null,
          initialStatus,
          date_of_birth || null,
        ],
      );
      const driver = driverResult.rows[0];

      for (const documentType of REQUIRED_DRIVER_DOCS) {
        await client.query(
          `INSERT INTO driver_documents (driver_id, document_type, file_url, file_name, verified, verified_at, notes)
           VALUES ($1,$2,NULL,$3,true,NOW(),$4)`,
          [
            driver.id,
            documentType,
            "test-mode-placeholder",
            "Auto-generated by DRIVER_TEST_MODE — not a real uploaded document.",
          ],
        );
      }

      const plan = PLANS.monthly;
      await client.query(
        `INSERT INTO driver_subscriptions (driver_id, plan_type, price, deliveries_limit, expires_at, status, paystack_reference)
         VALUES ($1,'monthly',$2,$3,NOW() + INTERVAL '30 days','active',$4)`,
        [driver.id, plan.price, plan.deliveries, "TEST_MODE_GRANT"],
      );

      return driver;
    });
  }

  static async verifyPassword(email, password) {
    const driver = await this.findByEmail(email);
    if (!driver) return null;

    const isValid = await bcrypt.compare(password, driver.password_hash);
    if (!isValid) return null;

    const { password_hash, ...safeDriver } = driver;
    return safeDriver;
  }

  static async updateProfile(driverId, data) {
    const { name, phone, vehicle_type, vehicle_plate } = data;
    return await super.update(this.tableName, driverId, {
      name,
      phone,
      vehicle_type,
      vehicle_plate,
    });
  }

  // Mirrors User.acceptTerms — the driver app previously had no
  // terms-acceptance mechanism of any kind (no column, no gate, no screen).
  static async acceptTerms(driverId) {
    return await super.update(this.tableName, driverId, {
      terms_accepted: true,
      terms_accepted_at: new Date(),
    });
  }

  // Mirrors User.deleteAccount's anonymization pattern (Apple/Google App
  // Store review requires an in-app self-service deletion path, an email
  // process alone doesn't satisfy it). Two extra guards a plain customer
  // doesn't need: a driver mid-delivery can't be anonymized without
  // stranding a customer's order, and a driver still owed money (payouts
  // are staged through DriverWallet, released on completion) can't be
  // anonymized without losing track of what's owed.
  static async deleteAccount(driverId) {
    const activeOrder = await this.query(
      `SELECT id FROM orders WHERE driver_id = $1
       AND status IN ('driver_assigned', 'driver_arrived_store', 'picked_up', 'in_transit', 'delivered')
       LIMIT 1`,
      [driverId],
    );
    if (activeOrder.rows.length) {
      throw new Error("ACTIVE_ORDER");
    }

    const wallet = await this.query(
      `SELECT wallet_balance, pending_balance FROM driver_wallets WHERE driver_id = $1`,
      [driverId],
    );
    const w = wallet.rows[0];
    if (w && (Number(w.wallet_balance) > 0 || Number(w.pending_balance) > 0)) {
      throw new Error("UNPAID_BALANCE");
    }

    const anonymizedEmail = `deleted-${driverId}@flash.invalid`;
    const password_hash = await bcrypt.hash(crypto.randomBytes(32).toString("hex"), 12);

    const result = await this.query(
      `UPDATE drivers
       SET name = 'Deleted Driver', email = $2, password_hash = $3,
           phone = NULL, vehicle_type = NULL, vehicle_plate = NULL,
           profile_photo_url = NULL, apple_id = NULL, google_id = NULL,
           push_token = NULL, is_online = false, status = 'suspended',
           updated_at = NOW()
       WHERE id = $1
       RETURNING id`,
      [driverId, anonymizedEmail, password_hash],
    );

    if (!result.rows.length) {
      throw new Error("Driver not found");
    }

    await this.query(
      `UPDATE refresh_tokens SET revoked_at = NOW() WHERE user_id = $1 AND role = 'driver' AND revoked_at IS NULL`,
      [driverId],
    );
  }

  static async getDocuments(driverId) {
    const result = await this.query(
      "SELECT document_type, verified, uploaded_at FROM driver_documents WHERE driver_id = $1",
      [driverId],
    );
    return result.rows;
  }

  static async uploadDocument(driverId, documentType, file) {
    const REQUIRED_DOCS = [
      "government_id",
      "drivers_license",
      "police_certified",
      "profile_photo",
      "vehicle_registration",
    ];

    const uploadResult = await s3Service.uploadFile(file, "flash-documents");

    // H-access-audit FIX: file_url used to be set to the permanent signed
    // URL Cloudinary returns on upload — now left NULL. public_id +
    // resource_type are stored instead, and a short-lived signed URL is
    // generated on demand wherever a document is actually served (see
    // Admin.getDriverById).
    const result = await this.query(
      `INSERT INTO driver_documents (driver_id, document_type, file_name, public_id, resource_type)
       VALUES ($1, $2, $3, $4, $5)
       ON CONFLICT (driver_id, document_type) DO UPDATE
       SET file_name=$3, public_id=$4, resource_type=$5, file_url=NULL, verified=false, uploaded_at=NOW()
       RETURNING *`,
      [driverId, documentType, file.originalname, uploadResult.publicId, uploadResult.resourceType],
    );

    const allDocs = await this.query(
      "SELECT document_type FROM driver_documents WHERE driver_id = $1",
      [driverId],
    );

    const uploadedTypes = allDocs.rows.map((r) => r.document_type);
    const allUploaded = REQUIRED_DOCS.every((d) => uploadedTypes.includes(d));

    if (allUploaded) {
      await this.query(
        "UPDATE drivers SET status='documents_submitted', updated_at=NOW() WHERE id=$1 AND status='pending_documents'",
        [driverId],
      );
    }

    return {
      document: result.rows[0],
      uploadedDocuments: uploadedTypes,
      allUploaded,
      message: allUploaded
        ? "All documents uploaded! Your application is now under review."
        : `Document uploaded. Still needed: ${REQUIRED_DOCS.filter((d) => !uploadedTypes.includes(d)).join(", ")}`,
    };
  }

  static async setOnlineStatus(driverId, online) {
    await this.query(
      "UPDATE drivers SET is_online=$1, updated_at=NOW() WHERE id=$2",
      [!!online, driverId],
    );
  }

  static async updateLocation(driverId, lat, lng, orderId, io) {
    // Drop (not persist/broadcast) any orderId the caller doesn't actually
    // own — otherwise a driver could POST a location tagged with any order,
    // and it would be broadcast live into that order's customer-facing
    // tracking room.
    if (orderId) {
      const ownsOrder = await this.query(
        "SELECT 1 FROM orders WHERE id=$1 AND driver_id=$2",
        [orderId, driverId],
      );
      if (ownsOrder.rows.length === 0) {
        orderId = null;
      }
    }

    await this.query(
      "UPDATE drivers SET current_lat=$1, current_lng=$2, updated_at=NOW() WHERE id=$3",
      [lat, lng, driverId],
    );

    const pingCount = (this._pingCounters.get(driverId) || 0) + 1;
    this._pingCounters.set(driverId, pingCount);

    if (pingCount % 5 === 0) {
      await this.query(
        "INSERT INTO driver_locations (driver_id, order_id, lat, lng) VALUES ($1, $2, $3, $4)",
        [driverId, orderId || null, lat, lng],
      );
    }

    if (io && orderId) {
      io.to(`order:${orderId}`).emit("driver_location", {
        driverId,
        orderId,
        lat,
        lng,
        timestamp: new Date().toISOString(),
      });

      await this.sendArrivalNotifications(driverId, orderId, lat, lng, io);
    }
  }

  static async sendArrivalNotifications(driverId, orderId, lat, lng, io) {
    const orderRow = await this.query(
      "SELECT user_id, dropoff_lat, dropoff_lng, is_cash_delivery, status FROM orders WHERE id=$1",
      [orderId],
    );

    if (orderRow.rows.length) {
      const order = orderRow.rows[0];
      const distKm = this.calculateDistance(
        lat,
        lng,
        order.dropoff_lat,
        order.dropoff_lng,
      );
      const mins = this.estimateMinutes(distKm);

      if (distKm !== null && ["in_transit", "driver_arrived_store"].includes(order.status)) {
        let milestone = null;
        if (distKm <= 0.15) {
          milestone = {
            key: "arrived",
            message: "Your driver has arrived!",
          };
        } else if (mins <= 2) {
          milestone = { key: "2min", message: "Driver is 2 minutes away!" };
        } else if (mins <= 5) {
          milestone = { key: "5min", message: "Driver is 5 minutes away" };
        } else if (mins <= 10) {
          milestone = {
            key: "10min",
            message: "Driver is about 10 minutes away",
          };
        } else if (mins <= 15) {
          milestone = {
            key: "15min",
            message: "Driver is about 15 minutes away",
          };
        }

        if (milestone) {
          io.to(`user:${order.user_id}`).emit("arrival_update", {
            orderId,
            milestone: milestone.key,
            message: milestone.message,
            distanceKm: distKm.toFixed(2),
            estimatedMins: mins,
          });

          if (order.is_cash_delivery && milestone.key === "5min") {
            io.to(`user:${order.user_id}`).emit("cash_reminder", {
              orderId,
              message:
                "Please have your cash ready — driver is almost there!",
            });
          }
        }
      }
    }
  }

  static calculateDistance(lat1, lng1, lat2, lng2) {
    if (!lat1 || !lng1 || !lat2 || !lng2) return null;
    const R = 6371;
    const dLat = ((lat2 - lat1) * Math.PI) / 180;
    const dLng = ((lng2 - lng1) * Math.PI) / 180;
    const a =
      Math.sin(dLat / 2) ** 2 +
      Math.cos((lat1 * Math.PI) / 180) *
        Math.cos((lat2 * Math.PI) / 180) *
        Math.sin(dLng / 2) ** 2;
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  }

  static estimateMinutes(km) {
    return Math.max(1, Math.round((km / 25) * 60));
  }

  static async getAvailableOrders(driverId) {
    // FIXED: Removed customer address and personal details from pre-accept order list — drivers should not see dropoff location or customer identity before accepting, privacy and safety risk
    //
    // FIXED (trusted driver): an order is excluded from this general pool
    // while it has an unexpired preferred_driver_id that is NOT this driver.
    // This is what makes the exclusivity window actually exclusive — without
    // this filter, "trusted driver" was purely cosmetic.
    // A return's reverse-delivery order (is_return_order=true) has no
    // order_items of its own — its item detail lives in
    // return_request_items instead, so item_count falls back to that count
    // for return orders rather than always showing 0.
    const sql = `
      SELECT o.id, o.order_number, o.status, o.delivery_mode, o.time_slot,
             o.driver_payout, o.is_cash_delivery, o.cash_to_collect,
             o.pickup_address, o.pickup_lat, o.pickup_lng,
             o.created_at, o.is_return_order,
             CASE WHEN o.is_return_order THEN (
               SELECT COUNT(*) FROM return_request_items rri
               JOIN return_requests rr ON rr.id = rri.return_id
               WHERE rr.return_order_id = o.id
             ) ELSE COUNT(oi.id) END AS item_count
      FROM orders o
      LEFT JOIN order_items oi ON oi.order_id = o.id
      WHERE o.status = 'waiting_for_driver'
        AND o.driver_id IS NULL
        AND (
          o.preferred_driver_id IS NULL
          OR o.preferred_driver_id = $1
          OR o.preferred_driver_expires_at IS NULL
          OR o.preferred_driver_expires_at <= NOW()
        )
      GROUP BY o.id
      ORDER BY o.created_at DESC
      LIMIT 20
    `;
    const result = await this.query(sql, [driverId]);
    return result.rows;
  }

  static async acceptOrder(driverId, orderId) {
    // NOTE: This method is not called by the live HTTP route.
    // backend/src/routes/driverRoutes.js wires POST /orders/:orderId/accept
    // to DriverController.acceptOrder, which calls
    // orderStateMachineService.assignDriver(orderId, driverId, {
    //   enforceTrustedDriverWindow: true
    // }) directly — that is where the trusted-driver exclusivity check now
    // lives (see orderStateMachineService.js). This model method is kept
    // for backward compatibility with any other internal callers, and is
    // updated with the same WHERE-clause guard for consistency / defense in
    // depth in case it is wired up elsewhere in the future.
    return await this.transaction(async (client) => {
      const result = await client.query(
        `UPDATE orders SET driver_id=$1, status='driver_assigned', delivery_payment_status='assigned', updated_at=NOW()
         WHERE id=$2
           AND status='waiting_for_driver'
           AND driver_id IS NULL
           AND (
             preferred_driver_id IS NULL
             OR preferred_driver_id = $1
             OR preferred_driver_expires_at IS NULL
             OR preferred_driver_expires_at <= NOW()
           )
         RETURNING *`,
        [driverId, orderId],
      );
      return result.rows[0];
    });
  }

  static async getEarnings(driverId) {
    const result = await this.query(
      `SELECT o.order_number, o.driver_payout, o.status, o.created_at,
              COUNT(oi.id) as item_count
       FROM orders o
       LEFT JOIN order_items oi ON oi.order_id = o.id
      WHERE o.driver_id = $1 AND o.status = 'completed'
       GROUP BY o.id
       ORDER BY o.created_at DESC`,
      [driverId],
    );

    const total = result.rows.reduce(
      (sum, r) => sum + parseFloat(r.driver_payout || 0),
      0,
    );
    return { orders: result.rows, totalEarnings: total.toFixed(2) };
  }

  static async getActiveOrder(driverId) {
    const result = await this.query(
      `SELECT o.id, o.order_number, o.status, o.delivery_mode, o.time_slot,
              o.total, o.driver_payout, o.pickup_address, o.dropoff_address,
              o.pickup_lat, o.pickup_lng, o.dropoff_lat, o.dropoff_lng,
              o.is_cash_delivery, o.created_at, o.is_return_order,
              u.name as customer_name, u.phone as customer_phone,
              CASE WHEN o.is_return_order THEN (
                SELECT COUNT(*) FROM return_request_items rri
                JOIN return_requests rr ON rr.id = rri.return_id
                WHERE rr.return_order_id = o.id
              ) ELSE COUNT(oi.id) END AS item_count
       FROM orders o
       LEFT JOIN users u ON u.id = o.user_id
       LEFT JOIN order_items oi ON oi.order_id = o.id
       WHERE o.driver_id = $1
         AND o.status IN ('driver_assigned', 'driver_arrived_store', 'picked_up', 'in_transit', 'delivered')
       GROUP BY o.id, u.id
       ORDER BY o.updated_at DESC
       LIMIT 1`,
      [driverId],
    );

    return result.rows[0] || null;
  }

  static async getNearby(lat, lng, limit = 10) {
    if (!lat || !lng) {
      const result = await this.query(
        `
        SELECT id, name, rating, total_deliveries, vehicle_type, vehicle_plate,
               profile_photo_url, is_online,
               NULL as distance_km,
               EXISTS(
                 SELECT 1 FROM orders o
                 WHERE o.driver_id = drivers.id
                   AND o.status IN ('driver_assigned','driver_arrived_store','picked_up','in_transit')
               ) as is_busy
        FROM drivers
        WHERE is_online = true AND status = 'approved'
        ORDER BY rating DESC LIMIT $1
      `,
        [limit],
      );
      return result.rows.map((d) => ({ ...d, estimated_fee: 35 }));
    }

    const sql = `
      SELECT d.id, d.name, d.rating, d.total_deliveries, d.vehicle_type, d.vehicle_plate,
             d.profile_photo_url, d.is_online,
             ROUND((6371 * acos(
               cos(radians($1)) * cos(radians(d.current_lat)) *
               cos(radians(d.current_lng) - radians($2)) +
               sin(radians($1)) * sin(radians(d.current_lat))
             ))::numeric, 1) AS distance_km,
             EXISTS(
               SELECT 1 FROM orders o
               WHERE o.driver_id = d.id
                 AND o.status IN ('driver_assigned','driver_arrived_store','picked_up','in_transit')
             ) as is_busy
      FROM drivers d
      WHERE d.is_online = true AND d.status = 'approved'
        AND d.current_lat IS NOT NULL AND d.current_lng IS NOT NULL
      ORDER BY distance_km ASC
      LIMIT $3
    `;
    const result = await this.query(sql, [
      parseFloat(lat),
      parseFloat(lng),
      limit,
    ]);
    return result.rows.map((d) => ({
      ...d,
      estimated_fee: d.distance_km
        ? Math.round(35 + parseFloat(d.distance_km || 0) * 2)
        : 35,
    }));
  }
}

module.exports = Driver;